### ISSUE TITLE
Maven proxy

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#92]
Implement Maven proxy repository (or Maven mirror) with authentication and cache support. Maven mirrors are described here: https://maven.apache.org/guides/mini/guide-mirror-settings.html

## Multi-remote

Maven proxy can be used to merge multiple remote repositories into single one. In this case, proxy repository is trying to access remotes one by one in specified order until find applicable artifact.

*Example: user uses Artipie Maven mirror to get artifacts from custom private repository and from Maven central, user configures Artipie Maven mirror to first search artifacts in private repository, and then from central, if artifact was not found in private repo.*

## Authentication

Proxy should be able to use authentication to access remote repository. The use case is when the user is giving access to different repositories through proxy or hiding actual credentials on proxy side.

## Caching

Proxy should be able to cache artifacts and metadata, the user can configure the TTL and size of the cache. Proxy needs to check HTTP cache control directives when pulling remote artifacts.
Artipie Maven proxy should use cache directives as well to avoid redundant downloads.

### Configuration

The suggested configuration for proxy repository for Artipie is:
```yaml
repository:
  type: maven-proxy
  remotes:
    - url: https://private.repo.com/maven # required
      username: admin # optional
      password: qwerty # optional
      cache: # optional
        ttl: 5d # optional
        maxSize: 10G # optional
    - url: https://repo.maven.apache.org/maven2
```

This job may be discussed and changed, also it can be boosted if needed.
